export const ADD_CHOSENPHOTO = "ADD_CHOSENPHOTO";
export const APPROVE_CHOSENPHOTO = "APPROVE_ CHOSENPHOTO";
export const REMOVE_CHOSENPHOTO = "REMOVE_CHOSENPHOTO";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_BASKET_ITEM = "REMOVE_BASKET_ITEM";
export const CALC_TOTAL_PRICE = "CALC_TOTAL_PRICE";
